spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/trading_engine?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 123456
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456

log:
  path: '/srv/logs/@project.artifactId@'

email:
  host: smtp.exmail.qq.com
  port: 465
  username: noreply@kangyonggan.com
  password: xxx
  expires-in: 10