spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/trading_engine?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 123456
  redis:
    database: 9
    host: 127.0.0.1
    port: 6379




